#!/bin/bash

#PBS -N pinseel_assn04.4
#PBS -q debug16core
#PBS -j oe
#PBS -m abe
#PBS -M eapinsee@uark.edu
#PBS -o pinseel_assn04.4.out.$PBS_JOBID
#PBS -l nodes=1:ppn=2
#PBS -l walltime=00:00:30:00

cd $PBS_O_WORKDIR

module load blast/2.6.0+
cat *.fasta > plant_mitochondrial_genomes.fasta
makeblastdb -in plant_mitochondrial_genomes.fasta -dbtype nucl -out plant_mitochondrial_genomes_database -title plant_mitochondrial_genomes_database
blastn -query ../watermelon_nt/nad4L.fasta -db plant_mitochondrial_genomes_database > pinseel_assn04.4.out 2>> pinseel_assn04.4.out